export const regioni = [
  {
    displayName: "Abruzzo",
    name: "abruzzo",
    iconPath: "/abruzzo.png",
  },
  {
    displayName: "Basilicata",
    name: "basilicata",
    iconPath: "/basilicata.png",
  },
  {
    displayName: "Calabria",
    name: "calabria",
    iconPath: "/calabria.png",
  },
  {
    displayName: "Campania",
    name: "campania",
    iconPath: "/campania.png",
  },
  {
    displayName: "Emilia-Romagna",
    name: "emilia-romagna",
    iconPath: "/emilia-romagna.png",
  },
  {
    displayName: "Friuli Venezia Giulia",
    name: "friuli-venezia-giulia",
    iconPath: "/friuli-venezia-giulia.png",
  },
  {
    displayName: "Lazio",
    name: "lazio",
    iconPath: "/lazio.png",
  },
  {
    displayName: "Liguria",
    name: "liguria",
    iconPath: "/liguria.png",
  },
  {
    displayName: "Lombardia",
    name: "lombardia",
    iconPath: "/lombardia.png",
  },
  {
    displayName: "Marche",
    name: "marche",
    iconPath: "/marche.png",
  },
  {
    displayName: "Molise",
    name: "molise",
    iconPath: "/molise.png",
  },
  {
    displayName: "Piemonte",
    name: "piemonte",
    iconPath: "/piemonte.png",
  },
  {
    displayName: "Puglia",
    name: "puglia",
    iconPath: "/puglia.png",
  },
  {
    displayName: "Sardegna",
    name: "sardegna",
    iconPath: "/sardegna.png",
  },
  {
    displayName: "Sicilia",
    name: "sicilia",
    iconPath: "/sicilia.png",
  },
  {
    displayName: "Toscana",
    name: "toscana",
    iconPath: "/toscana.png",
  },
  {
    displayName: "Trentino-Alto Adige",
    name: "trentino-alto-adige",
    iconPath: "/trentino-alto-adige.png",
  },
  {
    displayName: "Umbria",
    name: "umbria",
    iconPath: "/umbria.png",
  },
  {
    displayName: "Valle d'Aosta",
    name: "valle-daosta",
    iconPath: "/valle-d-aosta.png",
  },
  {
    displayName: "Veneto",
    name: "veneto",
    iconPath: "/veneto.png",
  },
];

export const startups: Startup[] = [
  {
    id: "d19f8e3e-1234-4b7d-9c5a-ef9a32ad2d8b",
    name: "Helpy Travel",
    tagline: "Empowering small BnBs with digital tools",
    description:
      "Helpy Travel offers a platform to improve guest experiences, increase revenue through upselling, and simplify management for small and medium-sized accommodations.",
    websiteUrl: "https://helpytravel.com",
    foundedYear: 2023,
    location: "Rome, Italy",
    status: "ACTIVE",
    features: [
      "Digital Guidebook",
      "Upselling Platform",
      "Customizable Solutions",
    ],
    category: "Health & Fitness",
    logoUrl: "https://example.com/logos/helpy-travel.png",
    thumbnailUrl: "https://example.com/thumbnails/helpy-travel-thumbnail.png",
    tags: ["Tourism", "Hospitality", "SaaS"],
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "ab2c9d8a-5678-4d0c-82a1-0f2f3e7b8c34",
    name: "Greenly",
    tagline: "Your partner in sustainable living",
    description:
      "Greenly develops tools and resources for individuals and businesses to reduce their carbon footprint and embrace sustainability.",
    websiteUrl: "https://greenly.com",
    foundedYear: 2021,
    location: "Milan, Italy",
    status: "ACTIVE",
    features: [
      "Carbon Calculator",
      "Eco-Friendly Recommendations",
      "Sustainability Reports",
    ],
    category: "Health & Fitness",
    logoUrl: "https://example.com/logos/greenly.png",
    thumbnailUrl: "https://example.com/thumbnails/greenly-thumbnail.png",
    tags: ["Sustainability", "Environment", "GreenTech"],
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "c4d9e6f3-9012-4a8d-91a5-9b8c7e2f0b43",
    name: "FoodieHub",
    tagline: "Connecting food lovers and local chefs",
    description:
      "FoodieHub is a platform where local chefs can showcase their talents and food lovers can discover unique dining experiences.",
    websiteUrl: "https://foodiehub.com",
    foundedYear: 2022,
    location: "Naples, Italy",
    status: "PENDING",
    features: ["Chef Discovery", "Event Booking", "Exclusive Recipes"],
    category: "Health & Fitness",
    logoUrl: "https://example.com/logos/foodiehub.png",
    thumbnailUrl: "https://example.com/thumbnails/foodiehub-thumbnail.png",
    tags: ["FoodTech", "Marketplace", "Experiences"],
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "e7f8g6h5-3456-4b1d-80a5-4b6c9d3e8f12",
    name: "SmartHome Solutions",
    tagline: "Innovating your home experience",
    description:
      "SmartHome Solutions integrates IoT devices to make your home smarter, safer, and more energy-efficient.",
    websiteUrl: "https://smarthomesolutions.com",
    foundedYear: 2020,
    location: "Turin, Italy",
    status: "ACTIVE",
    features: ["IoT Integration", "Energy Monitoring", "Remote Control"],
    category: "Health & Fitness",
    logoUrl: "https://example.com/logos/smarthome.png",
    thumbnailUrl: "https://example.com/thumbnails/smarthome-thumbnail.png",
    tags: ["IoT", "Smart Home", "Technology"],
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "g9h0i1j2-7890-4f5d-92c5-3a7b2d9f4e67",
    name: "EduGrow",
    tagline: "Learning made accessible",
    description:
      "EduGrow provides digital learning tools for students, teachers, and institutions to create personalized education journeys.",
    websiteUrl: "https://edugrow.com",
    foundedYear: 2019,
    location: "Florence, Italy",
    status: "ACTIVE",
    features: [
      "E-Learning Platform",
      "Virtual Classrooms",
      "AI-Powered Learning Paths",
    ],
    category: "Health & Fitness",
    logoUrl: "https://example.com/logos/edugrow.png",
    thumbnailUrl: "https://example.com/thumbnails/edugrow-thumbnail.png",
    tags: ["Education", "EdTech", "AI"],
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "h3i2j4k5-2345-4d8a-9b1c-8f7g9e2h6f45",
    name: "EcoFleet",
    tagline: "Greener logistics for a better future",
    description:
      "EcoFleet specializes in sustainable delivery solutions, optimizing routes to reduce emissions.",
    websiteUrl: "https://ecofleet.com",
    foundedYear: 2021,
    location: "Bologna, Italy",
    status: "ACTIVE",
    features: [
      "Route Optimization",
      "Eco-Friendly Vehicles",
      "Real-Time Tracking",
    ],
    logoUrl: "https://example.com/logos/ecofleet.png",
    thumbnailUrl: "https://example.com/thumbnails/ecofleet-thumbnail.png",
    tags: ["Logistics", "GreenTech", "Sustainability"],
    category: "Logistics",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "j5k6l7m8-4567-4f2d-83a1-0f6h9i7g5f43",
    name: "FitLife",
    tagline: "Your digital personal trainer",
    description:
      "FitLife provides personalized workout and nutrition plans through an AI-powered mobile app.",
    websiteUrl: "https://fitlife.com",
    foundedYear: 2020,
    location: "Rome, Italy",
    status: "ACTIVE",
    features: ["AI Workout Plans", "Diet Recommendations", "Progress Tracking"],
    logoUrl: "https://example.com/logos/fitlife.png",
    thumbnailUrl: "https://example.com/thumbnails/fitlife-thumbnail.png",
    tags: ["Fitness", "HealthTech", "AI"],
    category: "Health & Fitness",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "n9o1p2q3-7891-4g8a-92c1-3h6i8j7f4k12",
    name: "Urban Eats",
    tagline: "Discover your city's flavors",
    description:
      "Urban Eats connects food lovers with hidden culinary gems in their city.",
    websiteUrl: "https://urbaneats.com",
    foundedYear: 2018,
    location: "Naples, Italy",
    status: "ACTIVE",
    features: ["Restaurant Discovery", "Exclusive Offers", "Local Reviews"],
    logoUrl: "https://example.com/logos/urbaneats.png",
    thumbnailUrl: "https://example.com/thumbnails/urbaneats-thumbnail.png",
    tags: ["FoodTech", "Marketplace", "Local Businesses"],
    category: "Food & Beverage",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "r4s5t6u7-5678-4h3a-80b1-5f9g2h6i4j23",
    name: "SkillBoost",
    tagline: "Upskilling for the future workforce",
    description:
      "SkillBoost offers online courses and certifications in emerging industries.",
    websiteUrl: "https://skillboost.com",
    foundedYear: 2017,
    location: "Milan, Italy",
    status: "ACTIVE",
    features: [
      "Certification Programs",
      "Interactive Courses",
      "Career Guidance",
    ],
    logoUrl: "https://example.com/logos/skillboost.png",
    thumbnailUrl: "https://example.com/thumbnails/skillboost-thumbnail.png",
    tags: ["EdTech", "Career Development", "E-Learning"],
    category: "Education",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "v8w9x0y1-9012-4i7a-83a2-6g8h9i7f5l34",
    name: "AutoMate",
    tagline: "Simplifying vehicle ownership",
    description:
      "AutoMate provides digital tools for car maintenance, insurance management, and more.",
    websiteUrl: "https://automate.com",
    foundedYear: 2019,
    location: "Turin, Italy",
    status: "ACTIVE",
    features: ["Maintenance Reminders", "Insurance Tools", "Cost Tracking"],
    logoUrl: "https://example.com/logos/automate.png",
    thumbnailUrl: "https://example.com/thumbnails/automate-thumbnail.png",
    tags: ["Automotive", "InsurTech", "Digital Tools"],
    category: "Automotive",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "y2z3a4b5-2345-4j9d-81a2-7h8i9f6g5k45",
    name: "MedConnect",
    tagline: "Bridging patients and healthcare providers",
    description:
      "MedConnect simplifies patient-doctor interactions with a secure telemedicine platform.",
    websiteUrl: "https://medconnect.com",
    foundedYear: 2020,
    location: "Florence, Italy",
    status: "ACTIVE",
    features: [
      "Video Consultations",
      "Appointment Scheduling",
      "Health Records Management",
    ],
    logoUrl: "https://example.com/logos/medconnect.png",
    thumbnailUrl: "https://example.com/thumbnails/medconnect-thumbnail.png",
    tags: ["HealthTech", "Telemedicine", "Healthcare"],
    category: "Healthcare",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "c6d7e8f9-5678-4k1d-92a3-8f7g6h5i4j34",
    name: "Eventify",
    tagline: "Your event, your way",
    description:
      "Eventify is a platform for planning, managing, and promoting events of all sizes.",
    websiteUrl: "https://eventify.com",
    foundedYear: 2021,
    location: "Venice, Italy",
    status: "ACTIVE",
    features: ["Event Ticketing", "Venue Booking", "Marketing Tools"],
    logoUrl: "https://example.com/logos/eventify.png",
    thumbnailUrl: "https://example.com/thumbnails/eventify-thumbnail.png",
    tags: ["Event Management", "Marketplace", "Tech"],
    category: "Events",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "e9f0g1h2-7890-4l3d-83a4-9h8i7f5g6k56",
    name: "ArtSmart",
    tagline: "Empowering artists with technology",
    description:
      "ArtSmart offers a platform for artists to showcase, sell, and manage their work online.",
    websiteUrl: "https://artsmart.com",
    foundedYear: 2019,
    location: "Bologna, Italy",
    status: "ACTIVE",
    features: ["Online Gallery", "E-Commerce Tools", "Art Promotion"],
    logoUrl: "https://example.com/logos/artsmart.png",
    thumbnailUrl: "https://example.com/thumbnails/artsmart-thumbnail.png",
    tags: ["ArtTech", "E-Commerce", "Creativity"],
    category: "Art & Design",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "g1h2i3j4-3456-4m7d-92b5-7f6g5h4i3k23",
    name: "PetCarely",
    tagline: "Because your pet deserves the best",
    description:
      "PetCarely provides a subscription box for pet supplies and an online vet consultation service.",
    websiteUrl: "https://petcarely.com",
    foundedYear: 2022,
    location: "Milan, Italy",
    status: "PENDING",
    features: ["Subscription Boxes", "Vet Consultations", "Pet Care Resources"],
    logoUrl: "https://example.com/logos/petcarely.png",
    thumbnailUrl: "https://example.com/thumbnails/petcarely-thumbnail.png",
    tags: ["PetTech", "Subscription", "Health"],
    category: "Pets",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
  {
    id: "k5l6m7n8-5678-4n3d-83c6-9i7h8f5g4k45",
    name: "AgriTechGrow",
    tagline: "Modern solutions for sustainable farming",
    description:
      "AgriTechGrow integrates AI and IoT to optimize agricultural practices and increase yields.",
    websiteUrl: "https://agritechgrow.com",
    foundedYear: 2021,
    location: "Catania, Italy",
    status: "ACTIVE",
    features: ["IoT Sensors", "Crop Analytics", "Sustainability Reports"],
    logoUrl: "https://example.com/logos/agritechgrow.png",
    thumbnailUrl: "https://example.com/thumbnails/agritechgrow-thumbnail.png",
    tags: ["AgriTech", "IoT", "Sustainability"],
    category: "Agriculture",
    createdAt: "2024-12-24T12:00:00.000Z",
    updatedAt: "2024-12-24T12:00:00.000Z",
  },
];

export const allTags = Array.from(
  new Set(startups.flatMap((s) => s.tags))
).sort();

export interface Startup {
  id: string;
  name: string;
  tagline?: string;
  description?: string;
  websiteUrl?: string;
  foundedYear?: number;
  location?: string;
  status?: string;
  features: string[];
  logoUrl?: string;
  thumbnailUrl?: string;
  tags: string[];
  category?: string;
  createdAt?: string;
  updatedAt?: string;
}

export const categories = [
  "🏋️‍♀️ Health & Fitness",
  "🍔 Food & Beverage",
  "📚 Education",
  "🚚 Logistics",
  "✈️ Travel & Tourism",
  "🌱 Sustainability",
  "🏠 Real Estate",
  "💳 FinTech",
  "💡 EdTech",
  "🚜 AgriTech",
  "🎨 Art & Design",
  "🐾 Pets",
  "🏥 Healthcare",
  "🏡 IoT & Smart Home",
  "🎉 Event Management",
  "🛒 Marketplace",
  "♻️ GreenTech",
  "🚗 Automotive",
  "🛍️ E-Commerce",
  "📞 Telecommunications",
  "🤖 AI & Machine Learning",
  "🪙 Blockchain & Crypto",
  "🎮 Gaming",
  "📱 Social Media",
  "🔒 Cybersecurity",
  "📈 Digital Marketing",
  "🎥 Entertainment",
  "🕶️ VR & AR",
  "📊 Data Analytics",
  "⚖️ LegalTech",
  "🛡️ InsurTech",
  "🧬 Biotech",
  "🌍 CleanTech",
  "🏅 SportsTech",
  "📰 Media & Publishing",
  "🛒 Retail",
];
